name: cash
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.3


flutter:
  assets:
    - assets/icons/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.otf



  uses-material-design: true


